# base image
FROM continuumio/miniconda3:4.7.10

# load in the environment.yml file
ADD ./docker/environment.yml /

# Updating setuptools to remove a bug when updating conda
RUN conda update -n base -c defaults conda setuptools

# create the environment
RUN conda update -n base conda -y && conda env update
